#!/bin/env php
<?php
// This file is a part of the MyMirror Project, a PHP University Project.
//
// Copyright (c) 2012 Theodore R.Smith (theodore@phpexperts.pro)
// DSA-1024 Fingerprint: 10A0 6372 9092 85A2 BB7F  907B CB8B 654B E33B F1ED
// Provided by the PHP University (www.phpu.cc)
//
// This file is dually licensed under the terms of the following licenses:
// * Primary License: OSSAL - Open Source Software Alliance License
//   * Key points:
//       5.Redistributions of source code in any non-textual form (i.e.
//          binary or object form, etc.) must not be linked to software that is
//          released with a license that requires disclosure of source code
//          (ex: the GPL).
//       6.Redistributions of source code must be licensed under more than one
//          license and must not have the terms of the OSSAL removed.
//   * See http://repo.phpexperts.pro/license-ossal.html for complete details.
//
// * Secondary License: Creative Commons Attribution License v3.0
//   * Key Points:
//       * You are free:
//           * to copy, distribute, display, and perform the work
//           * to make non-commercial or commercial use of the work in its original form
//       * Under the following conditions:
//           * Attribution. You must give the original author credit. You must retain all
//             Copyright notices and you must include the sentence, "Based upon work from the
//             the PHP University (www.phpu.cc).", wherever you list contributors and authors.
//   * See http://creativecommons.org/licenses/by/3.0/ for complete details.

if (!isset($argv[1]))
{
	echo "mirror_page.php: input_url output_directory\n";
	return 1;
}

if (!isset($argv[2]))
{
	echo "ERROR: The output directory was not specificed.\n";
	return 2;
}

$output_directory = $argv[2];

// Create the directory if it doesn't exist.
if (!file_exists($output_directory))
{
	// 0775 = u+g rwx, a = rx
	// true = recursively create directories
    if (!(mkdir($output_directory, 0775, true)))
	{
		echo "Could not create directory: $output_directory";
		error_log("Could not create directory: $output_directory");
		exit;
	}
}


echo "Mirroring $argv[1] to $output_directory...\n"; flush();
system("httrack --user-agent 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.15 (KHTML, like Gecko) Chrome/10.0.612.3 Safari/534.15' --verbose --timeout=30 --continue --robots=0 --mirror '" . $argv[1] . "' --depth=2 '-*' '+*.css' '+*.js' '+*.jpg' '+*.gif' '+*.png' '+*.fla' '+*.swf' + '+*.flv' '+*.ico' -O " . $output_directory);
